name: hocus_focus
description: "HocusFocus project for ECE NTUA class course"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg : ^2.0.16
  table_calendar: ^3.1.3
  sqflite: ^2.4.1
  path: ^1.9.0
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  url_launcher: ^6.0.10
  shared_preferences: ^2.2.0
  flutter_native_splash: ^2.2.19
  fluttertoast: ^8.2.2
  audioplayers: ^6.1.0
  youtube_explode_dart: ^2.3.6
  audio_service: ^0.18.16
  vibration: ^1.8.4
  pattern_formatter: ^4.0.0
  flutter_masked_text2: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/nav_icons/
    - assets/images/wizard/
    - assets/images/items/
    - assets/images/spells/
  
  fonts:
    - family: AvolisseDEMO
      fonts:
        - asset: assets/fonts/AvolisseDEMO-Regular.ttf
          weight: 400
      
          
